version: "3.7"

services:
  db:
    image: "mysql:${MYSQL_TAG}"
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    labels:
      - "traefik.enable=false"
    networks:
      - internal

  wordpress:
    depends_on:
      - db
    image: "wordpress:${WORDPRESS_TAG}"
    volumes:
      - ./wp:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`${HTTP_HOST}`, `www.${HTTP_HOST}`)"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=lets-encrypt"
      - "traefik.port=80"
    networks:
      - internal
      - web

networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge
